try pdf 5#

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,6 +35,9 @@ jobs:
     - name: Verify deployment files
       run: ls -R book/_build/html
 
+    - name: Verify lec_slides deployment
+      run: ls -R book/_build/html/lec_slides || echo "lec_slides folder is missing"
+
     - name: Deploy book
       uses: JamesIves/github-pages-deploy-action@v4
       with:
